language: node_js

node_js:
  - "node"

git:
  depth: 10

branches:
  only:
    - master

before_script:
  - npm install

script:
  - npm run build

deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: dist
    skip_cleanup: true